[versions]
minecraft = "1.21.1"
neoForge = "21.1.215"
registrate = "MC1.21-1.3.0+62"
anvillib = "1.4.0+build.172"
anvilcraft = "1.5.2+hotfix.1650"
anvilcraft_guideme = "1.5.1-1+build.19"
modDevGradle = "2.0.78"
lombok = "8.7.1"
create = "6.0.6-107"
ponder = "1.0.56"
flywheel = "1.0.4-30"
guideme = "21.1.9"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-1.21.1", version.ref = "anvillib" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }
create = { group = "com.simibubi.create", name = "create-1.21.1", version.ref = "create" }
ponder = { group = "net.createmod.ponder", name = "Ponder-NeoForge-1.21.1", version.ref = "ponder" }
flywheelApi = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version.ref = "flywheel" }
anvilcraftguideme = { group = "dev.anvilcraft.guideme", name = "anvilcraft_guideme-neoforge-1.21.1", version.ref = "anvilcraft_guideme"}
guideme = { group = "org.appliedenergistics", name = "guideme", version.ref = "guideme" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
